alert("Welcome To Safeer's Website!")
alert("Error! Please enter a valid password.")
alert("Welcome to JavaScript Land...\nHappy Coding!")
alert("Welcome to JS Land...")
alert("Happy Coding!\nPrevent this page from creating additional dialogs.")
